# Generated by Django 5.0.6 on 2024-07-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookingroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingRoom',
        ),
    ]
