# Generated by Django 5.0.6 on 2024-07-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_hotel_addres_en_hotel_addres_ky_hotel_addres_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
